### PR TITLE
cloudscraper, update csrf_regexp, auth dict

### PR DESCRIPTION
**Pull request by UnusualPi**
handling for cloudflare bot protection
update csrf_regexp for new page format
update auth payloads for new dict structure

### CODE REVIEW

**Comment by coding4z** [comment]
@haochi any chance you can review/approve this PR? Many thanks for providing this library!

**Comment by ecoen66** [comment]
+1

**Comment by anthonysfancher** [comment]
+1

**Comment by sanghviharshit** [comment]
I think `cloudscraper` needs to be listed in requirements

**Comment by jcguu95** [comment]
Also there's a typo in line 60 of `main`. It should be

```
        pc.authenticate_password(email, password)
```

**Comment by BigSpringSnyder** [comment]
I want to use this API and open the account every morning using Selenium automatically. Using API, I wan to download all transactions, included just showed up in the account (but not fully posted) and balances of all the accounts. I would like to know few things.
1. Can I know if it will work. Can API bypass the 2FA and login automatically?
2. If I login in the morning after the banking hours, do all the transactions updated but not fully posted  get downloaded?
3. Can Posted balance and Available balance both be downloaded?


Thanks in advance.
Jay

**Comment by shubhampatwa30** [comment]
I am unable to login using the latest pull #21 .
It gave me this error first. ERROR:root:[Errno 2] No such file or directory: 'session.json'
If I create a json file with that name with {} value, it gives me this error personalcapital.personalcapital.LoginFailedException.
I tried to debug : 
        print(initial_csrf)
        print(csrf)
        print(auth_level)
Output:
None
None
None
Please help.

**Comment by hammem** [comment]
@UnusualPi , I also encountered this issue and realized just updating the User-Agent will satisfy CloudFlare's checks (see #24 ).  I'm sure there are many other ways to address, but the User-Agent tweak avoids adding a dependency to the library.

**Comment by UnusualPi** [comment]
> @UnusualPi , I also encountered this issue and realized just updating the User-Agent will satisfy CloudFlare's checks (see #24 ). I'm sure there are many other ways to address, but the User-Agent tweak avoids adding a dependency to the library.

I like this better than my solution, much cleaner without a new dependency.  I assume the user agent validation is the primary reason cloud flare would catch it so should work for most.

**Comment by brodia10** [comment]
> I am unable to login using the latest pull #21 . It gave me this error first. ERROR:root:[Errno 2] No such file or directory: 'session.json' If I create a json file with that name with {} value, it gives me this error personalcapital.personalcapital.LoginFailedException. I tried to debug : print(initial_csrf) print(csrf) print(auth_level) Output: None None None Please help.

I'm experiencing the same errors in the same situations.

**Comment by hammem** [comment]
> I'm experiencing the same errors in the same situations.

@brodia10 , try using #24 , it may resolve the issues

**Comment by brodia10** [comment]
> > I'm experiencing the same errors in the same situations.
> 
> @brodia10 , try using #24 , it may resolve the issues

@hammem thank you this worked wonderfully 👍

**Comment by banool** [comment]
Looks like @UnusualPi deleted their fork of this repo. I made the same changes they made in my own repo here: https://github.com/banool/personalcapital.

**Comment by hammem** [comment]
@banool , I think they deleted it to use the changes put up in #24 .  You may find this works well (at least it did for me as recently as this week).

**Pull request closed without merging**
